run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt          # Check code formatting
    - goimports      # Check import formatting
    - govet          # Examines Go source code and reports suspicious constructs
    - errcheck       # Check for unchecked errors
    - staticcheck    # Static analysis
    - unused         # Check for unused code
    - gosimple       # Simplify code
    - ineffassign    # Detect ineffectual assignments
    - typecheck      # Type-check code
    - goconst        # Find repeated strings that could be constants
    - misspell       # Find misspelled English words
    - unparam        # Find unused function parameters
    - nakedret       # Find naked returns in long functions
    - prealloc       # Find slice declarations that could be preallocated
    - exportloopref  # Check for exported loop variable references
    - nolintlint     # Check nolint directives
    - revive         # Fast, configurable, extensible, flexible linter
    - stylecheck     # Replacement for golint

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: publicscannerapi

  govet:
    check-shadowing: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: package-comments
      - name: var-naming
      - name: indent-error-flow
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: context-keys-type
      - name: context-as-argument

  stylecheck:
    checks: ["all", "-ST1003"]  # Disable ST1003: should not use underscores in Go names

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - goconst

    # Exclude certain revive rules in test files
    - path: _test\.go
      text: "should not use dot imports"
      linters:
        - revive

  max-issues-per-linter: 50
  max-same-issues: 3

  # Show only new issues
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
